server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Gzip para mejorar rendimiento
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_proxied any;
    gzip_vary on;

    location ~* \.(?:manifest|appcache|html?|xml|json)$ {
        expires -1;
        # add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        # add_header Pragma 'no-cache';
        # add_header Expires '0';
        # add_header Surrogate-Control 'no-store';
    }

    location ~* \.(?:css|js|woff|woff2|ttf|otf|eot|ico|svg|gif|jpe?g|png)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }
}
